# docker-compose.yml

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - url-shortener-net

  web:
    build: .
    container_name: url-shortener
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - url-shortener-net

networks:
  url-shortener-net:
    driver: bridge
