apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  labels:
    app: url-shortener
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001